# Generated by Django 4.2.11 on 2024-08-19 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_at', models.DateTimeField(auto_created=True)),
                ('Created_at', models.DateTimeField(auto_created=True)),
                ('text', models.TextField(max_length=240)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
