# Generated by Django 4.2.11 on 2024-08-25 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('echonet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echo',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='echo',
            name='Updated_at',
        ),
        migrations.AddField(
            model_name='echo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='echo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
