# Generated by Django 4.2.11 on 2025-03-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echonet', '0002_remove_echo_created_at_remove_echo_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echo',
            name='photo',
        ),
    ]
